ARG SERVER_NAME=""

ARG VIRTUAL_REPO_NAME=""

FROM ${SERVER_NAME}.jfrog.io/${VIRTUAL_REPO_NAME}/bitnami/node:10 AS builder
COPY package.json server.js /app/
RUN npm install --prefix /app

FROM ${SERVER_NAME}.jfrog.io/${VIRTUAL_REPO_NAME}/bitnami/node:10-prod

ARG VERSION=1.3
LABEL name="Node-10-hardened-app" \
      maintainer="support@support.dev" \
      vendor="NODE" \
      version="${VERSION}" \
      description="Hardended Node App Image"


COPY --from=builder /app/package.json /app/server.js /app/
COPY --from=builder /app/node_modules /app/node_modules

RUN useradd -r -u 1001 -g root nonroot

EXPOSE 3000

RUN chmod -R g+rwX /var/log

VOLUME /settings

RUN ln -sf /dev/stdout /var/log/app.log

USER nonroot

WORKDIR /app

ENTRYPOINT ["node"]

CMD ["server.js"]
